"""
Data Lineage Module - Core Implementation

Provides data lineage tracking for understanding data relationships,
transformations, and dependencies across the pipeline.

Implements DRY principle: Reuses dataclass patterns for consistent
lineage data structures across modules.
"""

from enum import Enum
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set, Any, Tuple
from datetime import datetime
from uuid import uuid4

from primedata.utils.log_utils import get_logger

logger = get_logger(__name__)


# ============================================================================
# ENUMS
# ============================================================================


class LineageEntityType(str, Enum):
    """Types of entities in data lineage."""

    DATASET = "dataset"  # Data collection/table
    FILE = "file"  # Physical file
    PROCESS = "process"  # Transformation/processing step
    PIPELINE = "pipeline"  # Pipeline execution
    MODEL = "model"  # ML model


class LineageRelationType(str, Enum):
    """Types of relationships in data lineage."""

    INPUT = "input"  # X is input to Y
    OUTPUT = "output"  # X is output from Y
    DERIVED = "derived"  # X is derived from Y
    DEPENDS_ON = "depends_on"  # X depends on Y
    CONTAINS = "contains"  # X contains Y
    GENERATED_BY = "generated_by"  # X was generated by Y


# ============================================================================
# DATA CLASSES
# ============================================================================


@dataclass
class LineageEntity:
    """Represents an entity in the data lineage graph."""

    entity_id: str
    entity_type: LineageEntityType
    name: str
    description: str = ""
    attributes: Dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __hash__(self) -> int:
        """Make entity hashable for use in sets."""
        return hash(self.entity_id)

    def __eq__(self, other) -> bool:
        """Compare entities by ID."""
        if not isinstance(other, LineageEntity):
            return False
        return self.entity_id == other.entity_id

    def __str__(self) -> str:
        return f"{self.entity_type.value}:{self.name} ({self.entity_id})"


@dataclass
class LineageRelationship:
    """Represents a relationship between entities."""

    relationship_id: str
    source_entity_id: str
    target_entity_id: str
    relationship_type: LineageRelationType
    properties: Dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __str__(self) -> str:
        return f"{self.source_entity_id} --[{self.relationship_type.value}]--> {self.target_entity_id}"


@dataclass
class LineageNode:
    """Node in the lineage graph with relationships."""

    entity: LineageEntity
    upstream_relationships: List[LineageRelationship] = field(default_factory=list)
    downstream_relationships: List[LineageRelationship] = field(default_factory=list)

    @property
    def upstream_entities(self) -> List[LineageEntity]:
        """Get entities upstream (inputs to this entity)."""
        # Implemented in manager
        return []

    @property
    def downstream_entities(self) -> List[LineageEntity]:
        """Get entities downstream (outputs from this entity)."""
        # Implemented in manager
        return []

    def __str__(self) -> str:
        return f"Node({self.entity}) | Up: {len(self.upstream_relationships)} | Down: {len(self.downstream_relationships)}"


@dataclass
class LineagePath:
    """A path through the lineage graph."""

    path_id: str
    entities: List[LineageEntity]
    relationships: List[LineageRelationship]
    length: int = 0

    def __post_init__(self):
        """Calculate path length."""
        self.length = len(self.entities)

    def __str__(self) -> str:
        entity_names = " -> ".join(e.name for e in self.entities)
        return f"Path({entity_names})"


# ============================================================================
# LINEAGE GRAPH
# ============================================================================


class LineageGraph:
    """
    Manages the data lineage graph.

    KISS principle: Simple graph data structure with query methods for
    retrieving upstream/downstream entities and paths.
    """

    def __init__(self):
        """Initialize lineage graph."""
        self.entities: Dict[str, LineageEntity] = {}
        self.relationships: Dict[str, LineageRelationship] = {}
        self.entity_relationships: Dict[str, List[LineageRelationship]] = {}
        logger.debug("LineageGraph initialized")

    def add_entity(self, entity: LineageEntity) -> None:
        """
        Add an entity to the graph.

        Args:
            entity: LineageEntity to add
        """
        self.entities[entity.entity_id] = entity
        if entity.entity_id not in self.entity_relationships:
            self.entity_relationships[entity.entity_id] = []
        logger.debug(f"Entity added: {entity}")

    def add_relationship(self, relationship: LineageRelationship) -> None:
        """
        Add a relationship between entities.

        Args:
            relationship: LineageRelationship to add
        """
        if relationship.source_entity_id not in self.entities:
            logger.warning(f"Source entity not found: {relationship.source_entity_id}")
            return

        if relationship.target_entity_id not in self.entities:
            logger.warning(f"Target entity not found: {relationship.target_entity_id}")
            return

        self.relationships[relationship.relationship_id] = relationship

        # Add to entity relationships index
        if relationship.source_entity_id not in self.entity_relationships:
            self.entity_relationships[relationship.source_entity_id] = []
        if relationship.target_entity_id not in self.entity_relationships:
            self.entity_relationships[relationship.target_entity_id] = []

        self.entity_relationships[relationship.source_entity_id].append(relationship)
        self.entity_relationships[relationship.target_entity_id].append(relationship)

        logger.debug(f"Relationship added: {relationship}")

    def get_entity(self, entity_id: str) -> Optional[LineageEntity]:
        """
        Get an entity by ID.

        Args:
            entity_id: ID of entity

        Returns:
            LineageEntity or None
        """
        return self.entities.get(entity_id)

    def get_relationships(self, entity_id: str) -> List[LineageRelationship]:
        """
        Get all relationships for an entity.

        Args:
            entity_id: ID of entity

        Returns:
            List of LineageRelationship
        """
        return self.entity_relationships.get(entity_id, [])

    def get_upstream_entities(self, entity_id: str) -> List[LineageEntity]:
        """
        Get entities that feed into this entity (inputs).

        Args:
            entity_id: ID of entity

        Returns:
            List of upstream LineageEntity
        """
        upstream = []
        relationships = self.get_relationships(entity_id)

        for rel in relationships:
            if rel.target_entity_id == entity_id and rel.relationship_type in [
                LineageRelationType.INPUT,
                LineageRelationType.DERIVED,
                LineageRelationType.DEPENDS_ON,
            ]:
                source = self.get_entity(rel.source_entity_id)
                if source:
                    upstream.append(source)

        return upstream

    def get_downstream_entities(self, entity_id: str) -> List[LineageEntity]:
        """
        Get entities that depend on this entity (outputs).

        Args:
            entity_id: ID of entity

        Returns:
            List of downstream LineageEntity
        """
        downstream = []
        relationships = self.get_relationships(entity_id)

        for rel in relationships:
            if rel.source_entity_id == entity_id and rel.relationship_type in [
                LineageRelationType.OUTPUT,
                LineageRelationType.GENERATED_BY,
            ]:
                target = self.get_entity(rel.target_entity_id)
                if target:
                    downstream.append(target)

        return downstream

    def find_path(
        self, source_id: str, target_id: str, max_depth: int = 10
    ) -> Optional[LineagePath]:
        """
        Find a path between two entities using BFS.

        Args:
            source_id: Starting entity ID
            target_id: Ending entity ID
            max_depth: Maximum path depth

        Returns:
            LineagePath or None if no path found
        """
        if source_id not in self.entities or target_id not in self.entities:
            return None

        if source_id == target_id:
            entity = self.get_entity(source_id)
            return LineagePath(
                path_id=f"path_{uuid4()}",
                entities=[entity],
                relationships=[],
            )

        # BFS to find path
        queue = [(source_id, [source_id], [])]
        visited = {source_id}

        while queue:
            current_id, path_ids, path_rels = queue.pop(0)

            if len(path_ids) > max_depth:
                continue

            downstream = self.get_downstream_entities(current_id)

            for next_entity in downstream:
                if next_entity.entity_id == target_id:
                    # Found the target
                    path_ids.append(target_id)

                    # Get relationships for this path
                    for i in range(len(path_ids) - 1):
                        rels = [
                            r
                            for r in self.relationships.values()
                            if r.source_entity_id == path_ids[i]
                            and r.target_entity_id == path_ids[i + 1]
                        ]
                        if rels:
                            path_rels.append(rels[0])

                    entities = [self.get_entity(eid) for eid in path_ids]
                    entities = [e for e in entities if e is not None]

                    return LineagePath(
                        path_id=f"path_{uuid4()}",
                        entities=entities,
                        relationships=path_rels,
                    )

                if next_entity.entity_id not in visited:
                    visited.add(next_entity.entity_id)
                    queue.append((next_entity.entity_id, path_ids + [next_entity.entity_id], path_rels))

        return None

    def get_graph_summary(self) -> Dict[str, Any]:
        """
        Get summary of the lineage graph.

        Returns:
            Summary dictionary with counts and statistics
        """
        entity_types = {}
        for entity in self.entities.values():
            entity_type = entity.entity_type.value
            entity_types[entity_type] = entity_types.get(entity_type, 0) + 1

        relationship_types = {}
        for rel in self.relationships.values():
            rel_type = rel.relationship_type.value
            relationship_types[rel_type] = relationship_types.get(rel_type, 0) + 1

        return {
            "total_entities": len(self.entities),
            "total_relationships": len(self.relationships),
            "entities_by_type": entity_types,
            "relationships_by_type": relationship_types,
            "timestamp": datetime.utcnow().isoformat(),
        }

    def export_to_dict(self) -> Dict[str, Any]:
        """
        Export graph to dictionary format for serialization.

        Returns:
            Dictionary representation of graph
        """
        entities_list = [
            {
                "entity_id": e.entity_id,
                "entity_type": e.entity_type.value,
                "name": e.name,
                "description": e.description,
                "attributes": e.attributes,
                "metadata": e.metadata,
            }
            for e in self.entities.values()
        ]

        relationships_list = [
            {
                "relationship_id": r.relationship_id,
                "source_entity_id": r.source_entity_id,
                "target_entity_id": r.target_entity_id,
                "relationship_type": r.relationship_type.value,
                "properties": r.properties,
                "metadata": r.metadata,
            }
            for r in self.relationships.values()
        ]

        return {
            "entities": entities_list,
            "relationships": relationships_list,
            "summary": self.get_graph_summary(),
        }
