"""Add enterprise data quality rules

Revision ID: 084bc8b5e18b
Revises: 35b5d0835265
Create Date: 2025-09-26 11:57:04.850264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy import inspect, text
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '084bc8b5e18b'
down_revision = '35b5d0835265'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def enum_exists(enum_name):
    """Check if a PostgreSQL ENUM type exists."""
    bind = op.get_bind()
    result = bind.execute(
        text("""
            SELECT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = :enum_name
            )
        """),
        {"enum_name": enum_name}
    )
    return result.scalar()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM types if they don't exist
    rulestatus_enum = postgresql.ENUM('DRAFT', 'ACTIVE', 'DEPRECATED', 'ARCHIVED', name='rulestatus', create_type=False)
    rulestatus_enum.create(op.get_bind(), checkfirst=True)
    
    ruleseverity_enum = postgresql.ENUM('ERROR', 'WARNING', 'INFO', name='ruleseverity', create_type=False)
    ruleseverity_enum.create(op.get_bind(), checkfirst=True)
    
    auditaction_enum = postgresql.ENUM('CREATE', 'UPDATE', 'DELETE', 'ACTIVATE', 'DEPRECATE', 'ARCHIVE', name='auditaction', create_type=False)
    auditaction_enum.create(op.get_bind(), checkfirst=True)
    
    # Create data_quality_compliance_reports table if it doesn't exist
    if not table_exists('data_quality_compliance_reports'):
        op.create_table('data_quality_compliance_reports',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('workspace_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('report_name', sa.String(length=255), nullable=False),
            sa.Column('report_type', sa.String(length=50), nullable=False),
            sa.Column('compliance_framework', sa.String(length=100), nullable=True),
            sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
            sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
            sa.Column('report_data', sa.JSON(), nullable=False),
            sa.Column('summary', sa.Text(), nullable=True),
            sa.Column('generated_by', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['workspace_id'], ['public.workspaces.id'], ),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
    
    # Create data_quality_rule_sets table if it doesn't exist
    if not table_exists('data_quality_rule_sets'):
            op.create_table('data_quality_rule_sets',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('workspace_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('version', sa.String(length=20), nullable=False),
            sa.Column('compliance_framework', sa.String(length=100), nullable=True),
            sa.Column('business_unit', sa.String(length=100), nullable=True),
            sa.Column('data_classification', sa.String(length=50), nullable=True),
            sa.Column('status', postgresql.ENUM('DRAFT', 'ACTIVE', 'DEPRECATED', 'ARCHIVED', name='rulestatus', create_type=False), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('created_by', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('approved_by', PG_UUID(as_uuid=True), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
            sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['workspace_id'], ['public.workspaces.id'], ),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
    
    # Create data_quality_rule_assignments table if it doesn't exist
    if not table_exists('data_quality_rule_assignments'):
            op.create_table('data_quality_rule_assignments',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('rule_set_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('product_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('assigned_by', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('is_override', sa.Boolean(), nullable=False),
            sa.Column('override_reason', sa.Text(), nullable=True),
            sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], ),
            sa.ForeignKeyConstraint(['rule_set_id'], ['public.data_quality_rule_sets.id'], ),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
    
    # Create data_quality_rules table if it doesn't exist
    if not table_exists('data_quality_rules'):
        op.create_table('data_quality_rules',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('product_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('workspace_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('rule_type', sa.String(length=50), nullable=False),
            sa.Column('severity', postgresql.ENUM('ERROR', 'WARNING', 'INFO', name='ruleseverity', create_type=False), nullable=False),
            sa.Column('status', postgresql.ENUM('DRAFT', 'ACTIVE', 'DEPRECATED', 'ARCHIVED', name='rulestatus', create_type=False), nullable=False),
            sa.Column('configuration', sa.JSON(), nullable=False),
            sa.Column('version', sa.Integer(), nullable=False),
            sa.Column('is_current', sa.Boolean(), nullable=False),
            sa.Column('parent_rule_id', PG_UUID(as_uuid=True), nullable=True),
            sa.Column('enabled', sa.Boolean(), nullable=False),
            sa.Column('created_by', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('updated_by', PG_UUID(as_uuid=True), nullable=True),
            sa.Column('approved_by', PG_UUID(as_uuid=True), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('compliance_tags', sa.JSON(), nullable=True),
            sa.Column('business_owner', sa.String(length=255), nullable=True),
            sa.Column('technical_owner', sa.String(length=255), nullable=True),
            sa.ForeignKeyConstraint(['parent_rule_id'], ['public.data_quality_rules.id'], ),
            sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], ),
            sa.ForeignKeyConstraint(['workspace_id'], ['public.workspaces.id'], ),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
    
    # Create data_quality_rule_audit table if it doesn't exist
    if not table_exists('data_quality_rule_audit'):
        op.create_table('data_quality_rule_audit',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('rule_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('action', postgresql.ENUM('CREATE', 'UPDATE', 'DELETE', 'ACTIVATE', 'DEPRECATE', 'ARCHIVE', name='auditaction', create_type=False), nullable=False),
            sa.Column('changed_by', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('old_values', sa.JSON(), nullable=True),
            sa.Column('new_values', sa.JSON(), nullable=True),
            sa.Column('change_reason', sa.Text(), nullable=True),
            sa.Column('ip_address', sa.String(length=45), nullable=True),
            sa.Column('user_agent', sa.Text(), nullable=True),
            sa.Column('session_id', sa.String(length=255), nullable=True),
            sa.ForeignKeyConstraint(['rule_id'], ['public.data_quality_rules.id'], ),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_quality_rule_audit')
    op.drop_table('data_quality_rules')
    op.drop_table('data_quality_rule_assignments')
    op.drop_table('data_quality_rule_sets')
    op.drop_table('data_quality_compliance_reports')
    # ### end Alembic commands ###
