"""Add billing profile model

Revision ID: 0b612b315803
Revises: 484bdf5ba39a
Create Date: 2025-09-27 10:49:50.659171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy import inspect, text
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0b612b315803'
down_revision = '484bdf5ba39a'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def enum_exists(enum_name):
    """Check if a PostgreSQL ENUM type exists."""
    bind = op.get_bind()
    result = bind.execute(
        text("""
            SELECT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = :enum_name
            )
        """),
        {"enum_name": enum_name}
    )
    return result.scalar()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create billingplan enum if it doesn't exist
    billingplan_enum = postgresql.ENUM('FREE', 'PRO', 'ENTERPRISE', name='billingplan', create_type=False)
    billingplan_enum.create(op.get_bind(), checkfirst=True)
    
    # Create billing_profiles table if it doesn't exist
    if not table_exists('billing_profiles'):
        op.create_table('billing_profiles',
            sa.Column('workspace_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
            sa.Column('plan', postgresql.ENUM('FREE', 'PRO', 'ENTERPRISE', name='billingplan', create_type=False), nullable=False),
            sa.Column('default_payment_method_id', sa.String(length=255), nullable=True),
            sa.Column('usage', sa.JSON(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['workspace_id'], ['public.workspaces.id'], ),
            sa.PrimaryKeyConstraint('workspace_id')
        , schema='public')
        op.create_index('idx_billing_profiles_plan', 'billing_profiles', ['plan'], unique=False)
        op.create_index('idx_billing_profiles_stripe_customer', 'billing_profiles', ['stripe_customer_id'], unique=False)
        op.create_index(op.f('ix_billing_profiles_stripe_customer_id'), 'billing_profiles', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_profiles_stripe_customer_id'), table_name='billing_profiles')
    op.drop_index('idx_billing_profiles_stripe_customer', table_name='billing_profiles')
    op.drop_index('idx_billing_profiles_plan', table_name='billing_profiles')
    op.drop_table('billing_profiles')
    # ### end Alembic commands ###
