"""add_vector_creation_enabled_and_use_case_description_to_products

Revision ID: 2fb9fd58c3fe
Revises: e566f8bb7e32
Create Date: 2026-01-10 13:43:19.498338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '2fb9fd58c3fe'
down_revision = 'e566f8bb7e32'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    try:
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        return column_name in columns
    except Exception:
        return False


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('products', 'vector_creation_enabled'):
        op.add_column('products', sa.Column('vector_creation_enabled', sa.Boolean(), nullable=False, server_default='true'))
    if not column_exists('products', 'use_case_description'):
        op.add_column('products', sa.Column('use_case_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if column_exists('products', 'vector_creation_enabled'):
        op.drop_column('products', 'vector_creation_enabled')
    if column_exists('products', 'use_case_description'):
        op.drop_column('products', 'use_case_description')
    # ### end Alembic commands ###
