"""add_promoted_version_to_products

Revision ID: 3028ce203362
Revises: df59fc2b6867
Create Date: 2025-09-25 17:03:11.727406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '3028ce203362'
down_revision = 'df59fc2b6867'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('products', 'promoted_version'):
        op.add_column('products', sa.Column('promoted_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'promoted_version')
    # ### end Alembic commands ###
