"""add_dq_violations_table

Revision ID: 35b5d0835265
Revises: 3028ce203362
Create Date: 2025-09-25 22:06:54.878780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy import inspect, text
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '35b5d0835265'
down_revision = '3028ce203362'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def enum_exists(enum_name):
    """Check if a PostgreSQL ENUM type exists."""
    bind = op.get_bind()
    result = bind.execute(
        text("""
            SELECT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = :enum_name
            )
        """),
        {"enum_name": enum_name}
    )
    return result.scalar()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create dqviolationseverity enum if it doesn't exist
    dqviolationseverity_enum = postgresql.ENUM('ERROR', 'WARNING', 'INFO', name='dqviolationseverity', create_type=False)
    dqviolationseverity_enum.create(op.get_bind(), checkfirst=True)
    
    # Create dq_violations table if it doesn't exist
    if not table_exists('dq_violations'):
        op.create_table('dq_violations',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('product_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('version', sa.Integer(), nullable=False),
            sa.Column('pipeline_run_id', PG_UUID(as_uuid=True), nullable=True),
            sa.Column('rule_name', sa.String(length=255), nullable=False),
            sa.Column('rule_type', sa.String(length=100), nullable=False),
            sa.Column('severity', postgresql.ENUM('ERROR', 'WARNING', 'INFO', name='dqviolationseverity', create_type=False), nullable=False),
            sa.Column('message', sa.Text(), nullable=False),
            sa.Column('details', sa.JSON(), nullable=True),
            sa.Column('affected_count', sa.Integer(), nullable=True),
            sa.Column('total_count', sa.Integer(), nullable=True),
            sa.Column('violation_rate', sa.Float(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], ),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
        op.create_index('idx_dq_violations_created_at', 'dq_violations', ['created_at'], unique=False)
        op.create_index('idx_dq_violations_product_version', 'dq_violations', ['product_id', 'version'], unique=False)
        op.create_index('idx_dq_violations_severity', 'dq_violations', ['severity'], unique=False)
        op.create_index(op.f('ix_dq_violations_id'), 'dq_violations', ['id'], unique=False)
        op.create_index(op.f('ix_dq_violations_pipeline_run_id'), 'dq_violations', ['pipeline_run_id'], unique=False)
        op.create_index(op.f('ix_dq_violations_product_id'), 'dq_violations', ['product_id'], unique=False)
        op.create_index(op.f('ix_dq_violations_version'), 'dq_violations', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dq_violations_version'), table_name='dq_violations')
    op.drop_index(op.f('ix_dq_violations_product_id'), table_name='dq_violations')
    op.drop_index(op.f('ix_dq_violations_pipeline_run_id'), table_name='dq_violations')
    op.drop_index(op.f('ix_dq_violations_id'), table_name='dq_violations')
    op.drop_index('idx_dq_violations_severity', table_name='dq_violations')
    op.drop_index('idx_dq_violations_product_version', table_name='dq_violations')
    op.drop_index('idx_dq_violations_created_at', table_name='dq_violations')
    op.drop_table('dq_violations')
    # ### end Alembic commands ###
