"""add_aird_enabled_to_products

Revision ID: 3bd677e2eacd
Revises: 2c3c514d31f1
Create Date: 2025-12-28 16:51:15.489237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '3bd677e2eacd'
down_revision = '2c3c514d31f1'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    try:
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        return column_name in columns
    except Exception:
        return False


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('products', 'aird_enabled'):
        op.add_column('products', sa.Column('aird_enabled', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if column_exists('products', 'aird_enabled'):
        op.drop_column('products', 'aird_enabled')
    # ### end Alembic commands ###
