"""add_pipeline_artifacts_table_for_enterprise_traceability

Revision ID: 4550eea71227
Revises: f3d3928ec4ad
Create Date: 2025-12-21 22:52:07.513665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '4550eea71227'
down_revision = 'f3d3928ec4ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    from sqlalchemy import inspect
    
    def table_exists(table_name):
        """Check if a table exists in the database."""
        bind = op.get_bind()
        inspector = inspect(bind)
        return table_name in inspector.get_table_names()
    
    # Create enum types explicitly (PostgreSQL requirement)
    # Use checkfirst=True to avoid errors if enum already exists
    artifacttype = postgresql.ENUM('JSONL', 'JSON', 'CSV', 'PDF', 'VECTOR', 'TEXT', 'BINARY', name='artifacttype', create_type=False)
    artifacttype.create(op.get_bind(), checkfirst=True)
    
    artifactstatus = postgresql.ENUM('ACTIVE', 'ARCHIVED', 'DELETED', 'PURGED', name='artifactstatus', create_type=False)
    artifactstatus.create(op.get_bind(), checkfirst=True)
    
    retentionpolicy = postgresql.ENUM('KEEP_FOREVER', 'DAYS_30', 'DAYS_90', 'DAYS_365', 'DELETE_ON_PROMOTE', 'ON_FAILURE_KEEP_90', name='retentionpolicy', create_type=False)
    retentionpolicy.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    # Create pipeline_artifacts table if it doesn't exist
    if not table_exists('pipeline_artifacts'):
        op.create_table('pipeline_artifacts',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('pipeline_run_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('workspace_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('product_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('version', sa.Integer(), nullable=False),
            sa.Column('stage_name', sa.String(length=100), nullable=False),
            sa.Column('artifact_type', postgresql.ENUM('JSONL', 'JSON', 'CSV', 'PDF', 'VECTOR', 'TEXT', 'BINARY', name='artifacttype', create_type=False), nullable=False),
            sa.Column('artifact_name', sa.String(length=255), nullable=False),
            sa.Column('minio_bucket', sa.String(length=255), nullable=False),
            sa.Column('minio_key', sa.String(length=1000), nullable=False),
            sa.Column('file_size', sa.BigInteger(), nullable=False),
            sa.Column('checksum', sa.String(length=64), nullable=True),
            sa.Column('minio_etag', sa.String(length=255), nullable=True),
            sa.Column('input_artifacts', sa.JSON(), nullable=True),
            sa.Column('artifact_metadata', sa.JSON(), nullable=True),
            sa.Column('status', postgresql.ENUM('ACTIVE', 'ARCHIVED', 'DELETED', 'PURGED', name='artifactstatus', create_type=False), nullable=False),
            sa.Column('retention_policy', postgresql.ENUM('KEEP_FOREVER', 'DAYS_30', 'DAYS_90', 'DAYS_365', 'DELETE_ON_PROMOTE', 'ON_FAILURE_KEEP_90', name='retentionpolicy', create_type=False), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('created_by', PG_UUID(as_uuid=True), nullable=True),
            sa.ForeignKeyConstraint(['created_by'], ['public.users.id'], ),
            sa.ForeignKeyConstraint(['pipeline_run_id'], ['public.pipeline_runs.id'], ),
            sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], ),
            sa.ForeignKeyConstraint(['workspace_id'], ['public.workspaces.id'], ),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
        op.create_index('idx_artifacts_minio_key', 'pipeline_artifacts', ['minio_key'], unique=False)
        op.create_index('idx_artifacts_product_version', 'pipeline_artifacts', ['product_id', 'version'], unique=False)
        op.create_index('idx_artifacts_retention', 'pipeline_artifacts', ['retention_policy', 'created_at'], unique=False)
        op.create_index('idx_artifacts_stage_type', 'pipeline_artifacts', ['stage_name', 'artifact_type'], unique=False)
        op.create_index('idx_artifacts_status_created', 'pipeline_artifacts', ['status', 'created_at'], unique=False)
        op.create_index(op.f('ix_pipeline_artifacts_created_at'), 'pipeline_artifacts', ['created_at'], unique=False)
        op.create_index(op.f('ix_pipeline_artifacts_id'), 'pipeline_artifacts', ['id'], unique=False)
        op.create_index(op.f('ix_pipeline_artifacts_minio_key'), 'pipeline_artifacts', ['minio_key'], unique=False)
        op.create_index(op.f('ix_pipeline_artifacts_pipeline_run_id'), 'pipeline_artifacts', ['pipeline_run_id'], unique=False)
        op.create_index(op.f('ix_pipeline_artifacts_product_id'), 'pipeline_artifacts', ['product_id'], unique=False)
        op.create_index(op.f('ix_pipeline_artifacts_stage_name'), 'pipeline_artifacts', ['stage_name'], unique=False)
        op.create_index(op.f('ix_pipeline_artifacts_status'), 'pipeline_artifacts', ['status'], unique=False)
        op.create_index(op.f('ix_pipeline_artifacts_version'), 'pipeline_artifacts', ['version'], unique=False)
        op.create_index(op.f('ix_pipeline_artifacts_workspace_id'), 'pipeline_artifacts', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_artifacts_workspace_id'), table_name='pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_artifacts_version'), table_name='pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_artifacts_status'), table_name='pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_artifacts_stage_name'), table_name='pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_artifacts_product_id'), table_name='pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_artifacts_pipeline_run_id'), table_name='pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_artifacts_minio_key'), table_name='pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_artifacts_id'), table_name='pipeline_artifacts')
    op.drop_index(op.f('ix_pipeline_artifacts_created_at'), table_name='pipeline_artifacts')
    op.drop_index('idx_artifacts_status_created', table_name='pipeline_artifacts')
    op.drop_index('idx_artifacts_stage_type', table_name='pipeline_artifacts')
    op.drop_index('idx_artifacts_retention', table_name='pipeline_artifacts')
    op.drop_index('idx_artifacts_product_version', table_name='pipeline_artifacts')
    op.drop_index('idx_artifacts_minio_key', table_name='pipeline_artifacts')
    op.drop_table('pipeline_artifacts')
    
    # Drop enum types
    postgresql.ENUM('JSONL', 'JSON', 'CSV', 'PDF', 'VECTOR', 'TEXT', 'BINARY', name='artifacttype', create_type=False).drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('ACTIVE', 'ARCHIVED', 'DELETED', 'PURGED', name='artifactstatus', create_type=False).drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM('KEEP_FOREVER', 'DAYS_30', 'DAYS_90', 'DAYS_365', 'DELETE_ON_PROMOTE', 'ON_FAILURE_KEEP_90', name='retentionpolicy', create_type=False).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
