"""Fix DataQualityRule relationships

Revision ID: 484bdf5ba39a
Revises: 084bc8b5e18b
Create Date: 2025-09-26 11:59:37.857886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484bdf5ba39a'
down_revision = '084bc8b5e18b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
