"""add_pipeline_runs

Revision ID: 56c47c1bfe30
Revises: 2507e4fa6f84
Create Date: 2025-09-20 17:51:43.751262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy import inspect, text
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '56c47c1bfe30'
down_revision = '2507e4fa6f84'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def enum_exists(enum_name):
    """Check if a PostgreSQL ENUM type exists."""
    bind = op.get_bind()
    result = bind.execute(
        text("""
            SELECT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = :enum_name
            )
        """),
        {"enum_name": enum_name}
    )
    return result.scalar()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create pipelinerunstatus enum if it doesn't exist
    pipelinerunstatus_enum = postgresql.ENUM('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='pipelinerunstatus', create_type=False)
    pipelinerunstatus_enum.create(op.get_bind(), checkfirst=True)
    
    # Create pipeline_runs table if it doesn't exist
    if not table_exists('pipeline_runs'):
        op.create_table('pipeline_runs',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('workspace_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('product_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('version', sa.Integer(), nullable=False),
            sa.Column('status', postgresql.ENUM('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='pipelinerunstatus', create_type=False), nullable=False),
            sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('dag_run_id', sa.String(length=255), nullable=True),
            sa.Column('metrics', sa.JSON(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], ),
            sa.ForeignKeyConstraint(['workspace_id'], ['public.workspaces.id'], ),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
        op.create_index('idx_pipeline_runs_dag_run_id', 'pipeline_runs', ['dag_run_id'], unique=False)
        op.create_index('idx_pipeline_runs_product_version', 'pipeline_runs', ['product_id', 'version'], unique=False)
        op.create_index('idx_pipeline_runs_workspace_id', 'pipeline_runs', ['workspace_id'], unique=False)
        op.create_index(op.f('ix_pipeline_runs_dag_run_id'), 'pipeline_runs', ['dag_run_id'], unique=False)
        op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
        op.create_index(op.f('ix_pipeline_runs_product_id'), 'pipeline_runs', ['product_id'], unique=False)
        op.create_index(op.f('ix_pipeline_runs_workspace_id'), 'pipeline_runs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_workspace_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_product_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_dag_run_id'), table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_workspace_id', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_product_version', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_dag_run_id', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
