"""remove_unused_pipeline_model

Revision ID: 74751c186a1e
Revises: 6ba2953c1cd4
Create Date: 2025-12-30 14:53:24.536789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74751c186a1e'
down_revision = '6ba2953c1cd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pipelines_id', table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index('ix_pipeline_artifacts_minio_key', table_name='pipeline_artifacts')
    op.create_index(op.f('ix_pipeline_artifacts_storage_key'), 'pipeline_artifacts', ['storage_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_artifacts_storage_key'), table_name='pipeline_artifacts')
    op.create_index('ix_pipeline_artifacts_minio_key', 'pipeline_artifacts', ['storage_key'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('config', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pipelines_pkey')
    , schema='public')
    op.create_index('ix_pipelines_id', 'pipelines', ['id'], unique=False)
    # ### end Alembic commands ###
