"""add_name_field_to_data_sources

Revision ID: 9ce47ec1464f
Revises: 4550eea71227
Create Date: 2025-12-22 22:37:56.522387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '9ce47ec1464f'
down_revision = '4550eea71227'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('data_sources', 'name'):
        # Add column as nullable first
        op.add_column('data_sources', sa.Column('name', sa.String(length=255), nullable=True))
        # Set default value for existing rows
        op.execute("UPDATE data_sources SET name = 'Unnamed Data Source' WHERE name IS NULL")
        # Now make it NOT NULL
        op.alter_column('data_sources', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'name')
    # ### end Alembic commands ###
