"""add_user_profile_fields

Revision ID: 9ef9ed084a5a
Revises: 0b612b315803
Create Date: 2025-09-27 12:44:27.514466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '9ef9ed084a5a'
down_revision = '0b612b315803'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('users', 'first_name'):
        op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=True))
    if not column_exists('users', 'last_name'):
        op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=True))
    if not column_exists('users', 'timezone'):
        op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
