"""add_chunking_and_embedding_config_to_products

Revision ID: a3ee91772c51
Revises: 56c47c1bfe30
Create Date: 2025-09-24 12:36:56.673504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'a3ee91772c51'
down_revision = '56c47c1bfe30'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('products', 'chunking_config'):
        op.add_column('products', sa.Column('chunking_config', sa.JSON(), nullable=True))
    if not column_exists('products', 'embedding_config'):
        op.add_column('products', sa.Column('embedding_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'embedding_config')
    op.drop_column('products', 'chunking_config')
    # ### end Alembic commands ###
