"""Initial migration with auth and workspaces

Revision ID: ab76775a482b
Revises: 
Create Date: 2025-09-18 18:32:12.505404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'ab76775a482b'
down_revision = None
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('data_sources'):
        op.create_table('data_sources',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('type', sa.String(length=100), nullable=False),
            sa.Column('config', sa.Text(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
        op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    if not table_exists('pipelines'):
        op.create_table('pipelines',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('config', sa.Text(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
        op.create_index(op.f('ix_pipelines_id'), 'pipelines', ['id'], unique=False)
    if not table_exists('users'):
        op.create_table('users',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('email', sa.String(length=255), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('first_name', sa.String(length=255), nullable=True),
            sa.Column('last_name', sa.String(length=255), nullable=True),
            sa.Column('timezone', sa.String(length=50), nullable=True),
            sa.Column('picture_url', sa.String(length=500), nullable=True),
            sa.Column('auth_provider', sa.Enum('GOOGLE', 'SIMPLE', 'NONE', name='authprovider'), nullable=False),
            sa.Column('google_sub', sa.String(length=255), nullable=True),
            sa.Column('roles', sa.JSON(), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=True),
            sa.Column('password_hash', sa.String(length=255), nullable=True),
            sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'),
            sa.Column('verification_token', sa.String(length=255), nullable=True),
            sa.Column('verification_token_expires', sa.DateTime(timezone=True), nullable=True),
            sa.Column('password_reset_token', sa.String(length=255), nullable=True),
            sa.Column('password_reset_token_expires', sa.DateTime(timezone=True), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
        op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=True)
        op.create_index(op.f('ix_users_password_reset_token'), 'users', ['password_reset_token'], unique=True)
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    if not table_exists('workspaces'):
        op.create_table('workspaces',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
        op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    if not table_exists('workspace_members'):
        op.create_table('workspace_members',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('workspace_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('user_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'EDITOR', 'VIEWER', name='workspacerole'), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
            sa.ForeignKeyConstraint(['workspace_id'], ['public.workspaces.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('workspace_id', 'user_id', name='unique_workspace_user')
        , schema='public')
        op.create_index(op.f('ix_workspace_members_id'), 'workspace_members', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_members_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_password_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pipelines_id'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
