"""add_raw_file_model_to_track_ingested_files

Revision ID: ae3d46973967
Revises: c51b69ec7fe7
Create Date: 2025-12-21 16:52:20.407799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'ae3d46973967'
down_revision = 'c51b69ec7fe7'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('raw_files'):
        op.create_table('raw_files',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('workspace_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('product_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('data_source_id', PG_UUID(as_uuid=True), nullable=True),
            sa.Column('version', sa.Integer(), nullable=False),
            sa.Column('filename', sa.String(length=500), nullable=False),
            sa.Column('file_stem', sa.String(length=500), nullable=False),
            sa.Column('minio_key', sa.String(length=1000), nullable=False),
            sa.Column('minio_bucket', sa.String(length=255), nullable=False),
            sa.Column('file_size', sa.Integer(), nullable=False),
            sa.Column('content_type', sa.String(length=255), nullable=True),
            sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['data_source_id'], ['public.data_sources.id'], ),
            sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], ),
            sa.ForeignKeyConstraint(['workspace_id'], ['public.workspaces.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('minio_key'),
            sa.UniqueConstraint('product_id', 'version', 'file_stem', name='uq_raw_file_product_version_stem')
        , schema='public')
        op.create_index('idx_raw_files_data_source', 'raw_files', ['data_source_id'], unique=False)
        op.create_index('idx_raw_files_file_stem', 'raw_files', ['file_stem'], unique=False)
        op.create_index('idx_raw_files_product_version', 'raw_files', ['product_id', 'version'], unique=False)
        op.create_index(op.f('ix_raw_files_data_source_id'), 'raw_files', ['data_source_id'], unique=False)
        op.create_index(op.f('ix_raw_files_file_stem'), 'raw_files', ['file_stem'], unique=False)
        op.create_index(op.f('ix_raw_files_id'), 'raw_files', ['id'], unique=False)
        op.create_index(op.f('ix_raw_files_product_id'), 'raw_files', ['product_id'], unique=False)
        op.create_index(op.f('ix_raw_files_workspace_id'), 'raw_files', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_files_workspace_id'), table_name='raw_files')
    op.drop_index(op.f('ix_raw_files_product_id'), table_name='raw_files')
    op.drop_index(op.f('ix_raw_files_id'), table_name='raw_files')
    op.drop_index(op.f('ix_raw_files_file_stem'), table_name='raw_files')
    op.drop_index(op.f('ix_raw_files_data_source_id'), table_name='raw_files')
    op.drop_index('idx_raw_files_product_version', table_name='raw_files')
    op.drop_index('idx_raw_files_file_stem', table_name='raw_files')
    op.drop_index('idx_raw_files_data_source', table_name='raw_files')
    op.drop_table('raw_files')
    # ### end Alembic commands ###
