"""remove_document_and_vector_metadata_tables

Revision ID: bda98fc65abe
Revises: a8b9c0d1e2f3
Create Date: 2025-12-27 16:17:52.789995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bda98fc65abe'
down_revision = 'a8b9c0d1e2f3'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    if not table_exists(table_name):
        return False
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def index_exists(table_name, index_name):
    """Check if an index exists on a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    if not table_exists(table_name):
        return False
    indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop vector_metadata table and its indexes if they exist
    if table_exists('vector_metadata'):
        indexes_to_drop = [
            'idx_vector_metadata_chunk_id',
            'idx_vector_metadata_collection',
            'idx_vector_metadata_field_name',
            'idx_vector_metadata_product_version',
            'ix_vector_metadata_chunk_id',
            'ix_vector_metadata_field_name',
            'ix_vector_metadata_id',
            'ix_vector_metadata_product_id'
        ]
        for index_name in indexes_to_drop:
            if index_exists('vector_metadata', index_name):
                op.drop_index(index_name, table_name='vector_metadata')
        op.drop_table('vector_metadata')
    
    # Drop document_metadata table and its indexes if they exist
    if table_exists('document_metadata'):
        indexes_to_drop = [
            'idx_document_metadata_chunk_id',
            'idx_document_metadata_field_name',
            'idx_document_metadata_product_version',
            'ix_document_metadata_chunk_id',
            'ix_document_metadata_id',
            'ix_document_metadata_product_id'
        ]
        for index_name in indexes_to_drop:
            if index_exists('document_metadata', index_name):
                op.drop_index(index_name, table_name='document_metadata')
        op.drop_table('document_metadata')
    
    # Create indexes on custom_playbooks if they don't exist
    if table_exists('custom_playbooks'):
        bind = op.get_bind()
        inspector = inspect(bind)
        existing_indices = [idx['name'] for idx in inspector.get_indexes('custom_playbooks')]
        if 'ix_custom_playbooks_owner_user_id' not in existing_indices:
            op.create_index(op.f('ix_custom_playbooks_owner_user_id'), 'custom_playbooks', ['owner_user_id'], unique=False)
        if 'ix_custom_playbooks_workspace_id' not in existing_indices:
            op.create_index(op.f('ix_custom_playbooks_workspace_id'), 'custom_playbooks', ['workspace_id'], unique=False)
    
    # Drop columns from products table if they exist
    columns_to_drop = [
        'aird_embedding_index_path',
        'aird_trust_score',
        'aird_playbook_id',
        'aird_optimizer_notes',
        'aird_chunks_indexed',
        'aird_policy',
        'aird_last_run_at',
        'aird_fingerprint'
    ]
    for column_name in columns_to_drop:
        if column_exists('products', column_name):
            op.drop_column('products', column_name)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('aird_fingerprint', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('aird_last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('aird_policy', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('aird_chunks_indexed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('aird_optimizer_notes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('aird_playbook_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('aird_trust_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('aird_embedding_index_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_custom_playbooks_workspace_id'), table_name='custom_playbooks')
    op.drop_index(op.f('ix_custom_playbooks_owner_user_id'), table_name='custom_playbooks')
    op.create_table('document_metadata',
    sa.Column('id', PG_UUID(as_uuid=True), autoincrement=False, nullable=False),
    sa.Column('product_id', PG_UUID(as_uuid=True), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('field_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('extra_tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], name='document_metadata_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_metadata_pkey')
    , schema='public')
    op.create_index('ix_document_metadata_product_id', 'document_metadata', ['product_id'], unique=False)
    op.create_index('ix_document_metadata_id', 'document_metadata', ['id'], unique=False)
    op.create_index('ix_document_metadata_chunk_id', 'document_metadata', ['chunk_id'], unique=False)
    op.create_index('idx_document_metadata_product_version', 'document_metadata', ['product_id', 'version'], unique=False)
    op.create_index('idx_document_metadata_field_name', 'document_metadata', ['field_name'], unique=False)
    op.create_index('idx_document_metadata_chunk_id', 'document_metadata', ['chunk_id'], unique=False)
    op.create_table('vector_metadata',
    sa.Column('id', PG_UUID(as_uuid=True), autoincrement=False, nullable=False),
    sa.Column('product_id', PG_UUID(as_uuid=True), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chunk_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('field_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], name='vector_metadata_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vector_metadata_pkey')
    , schema='public')
    op.create_index('ix_vector_metadata_product_id', 'vector_metadata', ['product_id'], unique=False)
    op.create_index('ix_vector_metadata_id', 'vector_metadata', ['id'], unique=False)
    op.create_index('ix_vector_metadata_field_name', 'vector_metadata', ['field_name'], unique=False)
    op.create_index('ix_vector_metadata_chunk_id', 'vector_metadata', ['chunk_id'], unique=False)
    op.create_index('idx_vector_metadata_product_version', 'vector_metadata', ['product_id', 'version'], unique=False)
    op.create_index('idx_vector_metadata_field_name', 'vector_metadata', ['field_name'], unique=False)
    op.create_index('idx_vector_metadata_collection', 'vector_metadata', ['collection_id'], unique=False)
    op.create_index('idx_vector_metadata_chunk_id', 'vector_metadata', ['chunk_id'], unique=False)
    # ### end Alembic commands ###
