"""add_aird_pipeline_tracking_to_pipeline_runs

Revision ID: c51b69ec7fe7
Revises: 9ef9ed084a5a
Create Date: 2025-12-15 12:25:10.232681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy import inspect, text
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c51b69ec7fe7'
down_revision = '9ef9ed084a5a'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def enum_exists(enum_name):
    """Check if a PostgreSQL ENUM type exists."""
    bind = op.get_bind()
    result = bind.execute(
        text("""
            SELECT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = :enum_name
            )
        """),
        {"enum_name": enum_name}
    )
    return result.scalar()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create aclaccesstype enum if it doesn't exist using postgresql.ENUM with checkfirst
    aclaccesstype_enum = postgresql.ENUM('FULL', 'INDEX', 'DOCUMENT', 'FIELD', name='aclaccesstype', create_type=False)
    aclaccesstype_enum.create(op.get_bind(), checkfirst=True)
    
    # Create acls table if it doesn't exist
    if not table_exists('acls'):
        op.create_table('acls',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('user_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('product_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('access_type', postgresql.ENUM('FULL', 'INDEX', 'DOCUMENT', 'FIELD', name='aclaccesstype', create_type=False), nullable=False),
            sa.Column('index_scope', sa.String(length=500), nullable=True),
            sa.Column('doc_scope', sa.String(length=500), nullable=True),
            sa.Column('field_scope', sa.String(length=500), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
        op.create_index('idx_acls_access_type', 'acls', ['access_type'], unique=False)
        op.create_index('idx_acls_product_id', 'acls', ['product_id'], unique=False)
        op.create_index('idx_acls_user_id', 'acls', ['user_id'], unique=False)
        op.create_index('idx_acls_user_product', 'acls', ['user_id', 'product_id'], unique=False)
        op.create_index(op.f('ix_acls_access_type'), 'acls', ['access_type'], unique=False)
        op.create_index(op.f('ix_acls_id'), 'acls', ['id'], unique=False)
        op.create_index(op.f('ix_acls_product_id'), 'acls', ['product_id'], unique=False)
        op.create_index(op.f('ix_acls_user_id'), 'acls', ['user_id'], unique=False)
    
    # Create document_metadata table if it doesn't exist
    if not table_exists('document_metadata'):
        op.create_table('document_metadata',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('product_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('version', sa.Integer(), nullable=False),
            sa.Column('chunk_id', sa.String(length=255), nullable=False),
            sa.Column('score', sa.Float(), nullable=True),
            sa.Column('source_file', sa.String(length=500), nullable=True),
            sa.Column('page_number', sa.Integer(), nullable=True),
            sa.Column('section', sa.String(length=255), nullable=True),
            sa.Column('field_name', sa.String(length=255), nullable=True),
            sa.Column('extra_tags', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], ),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
        op.create_index('idx_document_metadata_chunk_id', 'document_metadata', ['chunk_id'], unique=False)
        op.create_index('idx_document_metadata_field_name', 'document_metadata', ['field_name'], unique=False)
        op.create_index('idx_document_metadata_product_version', 'document_metadata', ['product_id', 'version'], unique=False)
        op.create_index(op.f('ix_document_metadata_chunk_id'), 'document_metadata', ['chunk_id'], unique=False)
        op.create_index(op.f('ix_document_metadata_id'), 'document_metadata', ['id'], unique=False)
        op.create_index(op.f('ix_document_metadata_product_id'), 'document_metadata', ['product_id'], unique=False)
    
    # Create vector_metadata table if it doesn't exist
    if not table_exists('vector_metadata'):
        op.create_table('vector_metadata',
            sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('product_id', PG_UUID(as_uuid=True), nullable=False),
            sa.Column('version', sa.Integer(), nullable=False),
            sa.Column('collection_id', sa.String(length=255), nullable=False),
            sa.Column('chunk_id', sa.String(length=255), nullable=False),
            sa.Column('page_number', sa.Integer(), nullable=True),
            sa.Column('section', sa.String(length=255), nullable=True),
            sa.Column('field_name', sa.String(length=255), nullable=True),
            sa.Column('tags', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['product_id'], ['public.products.id'], ),
            sa.PrimaryKeyConstraint('id')
        , schema='public')
        op.create_index('idx_vector_metadata_chunk_id', 'vector_metadata', ['chunk_id'], unique=False)
        op.create_index('idx_vector_metadata_collection', 'vector_metadata', ['collection_id'], unique=False)
        op.create_index('idx_vector_metadata_field_name', 'vector_metadata', ['field_name'], unique=False)
        op.create_index('idx_vector_metadata_product_version', 'vector_metadata', ['product_id', 'version'], unique=False)
        op.create_index(op.f('ix_vector_metadata_chunk_id'), 'vector_metadata', ['chunk_id'], unique=False)
        op.create_index(op.f('ix_vector_metadata_field_name'), 'vector_metadata', ['field_name'], unique=False)
        op.create_index(op.f('ix_vector_metadata_id'), 'vector_metadata', ['id'], unique=False)
        op.create_index(op.f('ix_vector_metadata_product_id'), 'vector_metadata', ['product_id'], unique=False)
    
    # Add columns to pipeline_runs if they don't exist
    if not column_exists('pipeline_runs', 'stage_metrics'):
        op.add_column('pipeline_runs', sa.Column('stage_metrics', sa.JSON(), nullable=True))
    if not column_exists('pipeline_runs', 'aird_stages_completed'):
        op.add_column('pipeline_runs', sa.Column('aird_stages_completed', sa.JSON(), nullable=True))
    
    # Add columns to products if they don't exist
    if not column_exists('products', 'playbook_id'):
        op.add_column('products', sa.Column('playbook_id', sa.String(length=50), nullable=True))
    if not column_exists('products', 'preprocessing_stats'):
        op.add_column('products', sa.Column('preprocessing_stats', sa.JSON(), nullable=True))
    if not column_exists('products', 'trust_score'):
        op.add_column('products', sa.Column('trust_score', sa.Float(), nullable=True))
    if not column_exists('products', 'readiness_fingerprint'):
        op.add_column('products', sa.Column('readiness_fingerprint', sa.JSON(), nullable=True))
    
    # Create policystatus enum type first (before using it in add_column)
    policystatus_enum = postgresql.ENUM('PASSED', 'FAILED', 'WARNINGS', 'UNKNOWN', name='policystatus', create_type=False)
    policystatus_enum.create(op.get_bind(), checkfirst=True)
    
    if not column_exists('products', 'policy_status'):
        op.add_column('products', sa.Column('policy_status', postgresql.ENUM('PASSED', 'FAILED', 'WARNINGS', 'UNKNOWN', name='policystatus', create_type=False), nullable=True))
    if not column_exists('products', 'policy_violations'):
        op.add_column('products', sa.Column('policy_violations', sa.JSON(), nullable=True))
    if not column_exists('products', 'chunk_metrics'):
        op.add_column('products', sa.Column('chunk_metrics', sa.JSON(), nullable=True))
    if not column_exists('products', 'validation_summary_path'):
        op.add_column('products', sa.Column('validation_summary_path', sa.String(length=500), nullable=True))
    if not column_exists('products', 'trust_report_path'):
        op.add_column('products', sa.Column('trust_report_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'trust_report_path')
    op.drop_column('products', 'validation_summary_path')
    op.drop_column('products', 'chunk_metrics')
    op.drop_column('products', 'policy_violations')
    op.drop_column('products', 'policy_status')
    # Drop policystatus enum type
    sa.Enum(name='policystatus').drop(op.get_bind(), checkfirst=True)
    op.drop_column('products', 'readiness_fingerprint')
    op.drop_column('products', 'trust_score')
    op.drop_column('products', 'preprocessing_stats')
    op.drop_column('products', 'playbook_id')
    op.drop_column('pipeline_runs', 'aird_stages_completed')
    op.drop_column('pipeline_runs', 'stage_metrics')
    op.drop_index(op.f('ix_vector_metadata_product_id'), table_name='vector_metadata')
    op.drop_index(op.f('ix_vector_metadata_id'), table_name='vector_metadata')
    op.drop_index(op.f('ix_vector_metadata_field_name'), table_name='vector_metadata')
    op.drop_index(op.f('ix_vector_metadata_chunk_id'), table_name='vector_metadata')
    op.drop_index('idx_vector_metadata_product_version', table_name='vector_metadata')
    op.drop_index('idx_vector_metadata_field_name', table_name='vector_metadata')
    op.drop_index('idx_vector_metadata_collection', table_name='vector_metadata')
    op.drop_index('idx_vector_metadata_chunk_id', table_name='vector_metadata')
    op.drop_table('vector_metadata')
    op.drop_index(op.f('ix_document_metadata_product_id'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_id'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_chunk_id'), table_name='document_metadata')
    op.drop_index('idx_document_metadata_product_version', table_name='document_metadata')
    op.drop_index('idx_document_metadata_field_name', table_name='document_metadata')
    op.drop_index('idx_document_metadata_chunk_id', table_name='document_metadata')
    op.drop_table('document_metadata')
    op.drop_index(op.f('ix_acls_user_id'), table_name='acls')
    op.drop_index(op.f('ix_acls_product_id'), table_name='acls')
    op.drop_index(op.f('ix_acls_id'), table_name='acls')
    op.drop_index(op.f('ix_acls_access_type'), table_name='acls')
    op.drop_index('idx_acls_user_product', table_name='acls')
    op.drop_index('idx_acls_user_id', table_name='acls')
    op.drop_index('idx_acls_product_id', table_name='acls')
    op.drop_index('idx_acls_access_type', table_name='acls')
    op.drop_table('acls')
    # ### end Alembic commands ###
