"""update_chunking_config_for_hybrid_approach

Revision ID: df59fc2b6867
Revises: a3ee91772c51
Create Date: 2025-09-24 15:17:20.007022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df59fc2b6867'
down_revision = 'a3ee91772c51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
