"""add_playbook_selection_metadata_to_products

Revision ID: f3777117c808
Revises: 9ce47ec1464f
Create Date: 2025-12-23 19:30:48.572542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'f3777117c808'
down_revision = '9ce47ec1464f'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('products', 'playbook_selection'):
        op.add_column('products', sa.Column('playbook_selection', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'playbook_selection')
    # ### end Alembic commands ###
