"""add_status_and_validation_fields_to_raw_files

Revision ID: f3d3928ec4ad
Revises: ae3d46973967
Create Date: 2025-12-21 16:57:07.931845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'f3d3928ec4ad'
down_revision = 'ae3d46973967'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first (PostgreSQL requires explicit enum creation)
    rawfilestatus_enum = sa.Enum('INGESTED', 'PROCESSING', 'PROCESSED', 'FAILED', 'DELETED', name='rawfilestatus', create_type=True)
    rawfilestatus_enum.create(op.get_bind(), checkfirst=True)
    
    # Add columns with default value for existing rows (only if they don't exist)
    if not column_exists('raw_files', 'status'):
        op.add_column('raw_files', sa.Column('status', rawfilestatus_enum, nullable=False, server_default='INGESTED'))
    if not column_exists('raw_files', 'file_checksum'):
        op.add_column('raw_files', sa.Column('file_checksum', sa.String(length=64), nullable=True))
    if not column_exists('raw_files', 'minio_etag'):
        op.add_column('raw_files', sa.Column('minio_etag', sa.String(length=255), nullable=True))
    if not column_exists('raw_files', 'processed_at'):
        op.add_column('raw_files', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    if not column_exists('raw_files', 'error_message'):
        op.add_column('raw_files', sa.Column('error_message', sa.Text(), nullable=True))
    
    # Check if index exists before creating it
    bind = op.get_bind()
    inspector = inspect(bind)
    try:
        existing_indices = [idx['name'] for idx in inspector.get_indexes('raw_files')]
        if 'idx_raw_files_status' not in existing_indices:
            op.create_index('idx_raw_files_status', 'raw_files', ['status'], unique=False)
    except Exception:
        # If we can't check indices, just skip creating them
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_raw_files_status', table_name='raw_files')
    op.drop_column('raw_files', 'error_message')
    op.drop_column('raw_files', 'processed_at')
    op.drop_column('raw_files', 'minio_etag')
    op.drop_column('raw_files', 'file_checksum')
    op.drop_column('raw_files', 'status')
    # Drop enum type
    sa.Enum(name='rawfilestatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
