"""initial history_assessment schema

Revision ID: 0001_initial_history_assessment_schema
Revises:
Create Date: 2026-06-10

Mirror of app/backend/db/sql/0001_initial_history_assessment_schema.sql.
Hand-authored — NOT autogenerated. Any change here must be reflected in
the .sql snapshot in the same commit.

Preconditions handled out-of-band:
- Schema `history_assessment` already exists.
- The DB user has CREATE on the schema.

pgcrypto is installed by upgrade() if the user has CREATE EXTENSION privilege.
If that fails in your environment, set HISTORY_UUID_SOURCE=python in .env;
the ORM will then generate UUIDs in Python and pgcrypto becomes unnecessary.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID

from config import settings

# revision identifiers, used by Alembic.
revision = "0001_initial_history_assessment_schema"
down_revision = None
branch_labels = None
depends_on = None

SCHEMA = settings.history_db_schema


def _uuid_server_default() -> sa.text | None:
    """Return the SQL default for UUID columns, or None when generating in Python."""
    if settings.history_uuid_source == "postgres":
        return sa.text("gen_random_uuid()")
    return None


def upgrade() -> None:
    # 1. Extension. Idempotent. Skipped when UUIDs come from Python.
    if settings.history_uuid_source == "postgres":
        op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # 2a. Users
    op.create_table(
        "users",
        sa.Column("user_id", sa.Text(), primary_key=True),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("department", sa.Text(), nullable=True),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        schema=SCHEMA,
    )
    op.execute(
        f"COMMENT ON TABLE {SCHEMA}.users IS "
        f"'SSO-authenticated users of ARC. user_id is the Lilly SSO subject claim.'"
    )
    op.execute(
        f"COMMENT ON COLUMN {SCHEMA}.users.role IS "
        f"'Job role from MS Graph; populated lazily, may be NULL.'"
    )

    # 2b. Assessment runs
    op.create_table(
        "assessment_runs",
        sa.Column(
            "run_id",
            UUID(as_uuid=True),
            primary_key=True,
            server_default=_uuid_server_default(),
        ),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("source_name", sa.Text(), nullable=False),
        sa.Column("source_ref", JSONB(), nullable=True),
        sa.Column("table_group", sa.Text(), nullable=True),
        sa.Column("overall_score", sa.Integer(), nullable=False),
        sa.Column("tier", sa.Text(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            [f"{SCHEMA}.users.user_id"],
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "source_type IN ('csv','db','s3')", name="ck_runs_source_type"
        ),
        sa.CheckConstraint(
            "tier IN ('green','yellow','red')", name="ck_runs_tier"
        ),
        sa.CheckConstraint(
            "overall_score BETWEEN 0 AND 100", name="ck_runs_overall_score"
        ),
        schema=SCHEMA,
    )
    # DESC on created_at — done with raw SQL because Alembic's create_index
    # doesn't expose per-column ordering for btree.
    op.execute(
        f"CREATE INDEX idx_runs_user_recent "
        f"ON {SCHEMA}.assessment_runs (user_id, created_at DESC)"
    )
    op.create_index(
        "idx_runs_source_ref_gin",
        "assessment_runs",
        ["source_ref"],
        schema=SCHEMA,
        postgresql_using="gin",
    )
    op.execute(
        f"COMMENT ON COLUMN {SCHEMA}.assessment_runs.source_ref IS "
        f"'Non-secret connection metadata only — host/db/schema/bucket/key. "
        f"NEVER passwords or tokens.'"
    )

    # 2c. Per-table results
    op.create_table(
        "table_assessments",
        sa.Column(
            "table_assessment_id",
            UUID(as_uuid=True),
            primary_key=True,
            server_default=_uuid_server_default(),
        ),
        sa.Column("run_id", UUID(as_uuid=True), nullable=False),
        sa.Column("table_name", sa.Text(), nullable=False),
        sa.Column("table_group", sa.Text(), nullable=True),
        sa.Column("table_score", sa.Integer(), nullable=False),
        sa.Column("tier", sa.Text(), nullable=False),
        sa.Column("dimension_scores", JSONB(), nullable=False),
        sa.Column("findings", JSONB(), nullable=False),
        sa.Column("strengths", JSONB(), nullable=False),
        sa.Column("recommendations", JSONB(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            [f"{SCHEMA}.assessment_runs.run_id"],
            ondelete="CASCADE",
        ),
        sa.CheckConstraint(
            "tier IN ('green','yellow','red')", name="ck_ta_tier"
        ),
        sa.CheckConstraint(
            "table_score BETWEEN 0 AND 100", name="ck_ta_table_score"
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "idx_ta_run",
        "table_assessments",
        ["run_id"],
        schema=SCHEMA,
    )
    op.create_index(
        "idx_ta_dim_scores_gin",
        "table_assessments",
        ["dimension_scores"],
        schema=SCHEMA,
        postgresql_using="gin",
    )
    # jsonb_path_ops for findings — better for @> containment queries.
    op.execute(
        f"CREATE INDEX idx_ta_findings_gin "
        f"ON {SCHEMA}.table_assessments USING GIN (findings jsonb_path_ops)"
    )


def downgrade() -> None:
    # Drop in reverse FK order: table_assessments → assessment_runs → users.
    # Indexes drop with their tables. pgcrypto extension is left in place
    # (it's database-wide and may be used by other apps).
    op.drop_table("table_assessments", schema=SCHEMA)
    op.drop_table("assessment_runs", schema=SCHEMA)
    op.drop_table("users", schema=SCHEMA)
