"""Markdown export endpoint — generates a downloadable action plan from a
SchemaAssessment. Single source of truth: the FE downloads this directly,
never rebuilds markdown on the client.
"""
from __future__ import annotations

from fastapi import APIRouter, Depends
from fastapi.responses import Response

from core.models import SchemaAssessment
from dependencies import CurrentUser, require_user

router = APIRouter(prefix="/export", tags=["export"])


def _render_markdown(assessment: SchemaAssessment) -> str:
    a = assessment
    base_score = a.base_score if a.base_score is not None else a.overall_score
    lines: list[str] = []

    lines.append(f"# AI Readiness Assessment — {a.verdict}")
    lines.append("")
    if base_score != a.overall_score:
        lines.append(
            f"**Governed score:** {a.overall_score}/100 · "
            f"**Base readiness:** {base_score}/100 · "
            f"{a.assessed_count} tables assessed · "
            f"{a.reference_count} reference (excluded)"
        )
    else:
        lines.append(
            f"**Score:** {a.overall_score}/100 · "
            f"{a.assessed_count} tables assessed · "
            f"{a.reference_count} reference (excluded)"
        )
    if a.gated_by:
        status = f"Gated — {len(a.gated_by)} blocker(s) must be resolved."
        if base_score != a.overall_score:
            status += " Governed score reflects the blocker cap; base readiness is shown before governance gating."
        lines.append(f"\n**Status:** {status}")
    lines.append("")

    # Action items
    if a.action_groups:
        lines.append("## Action Items")
        lines.append("")
        for ag in a.action_groups:
            lines.append(f"### {ag.severity.upper()}: {ag.issue}")
            lines.append(f"**Dimension:** {ag.dimension_id}")
            tables_str = ", ".join(ag.affected_tables)
            lines.append(f"**Affects:** {tables_str} ({ag.table_count} table{'s' if ag.table_count != 1 else ''})")
            lines.append(f"**Do this:** {ag.recommended_fix}")
            if ag.explanation:
                lines.append("")
                lines.append(f"> **What this means:** {ag.explanation.what}")
                lines.append(f"> **Why it matters:** {ag.explanation.why}")
                lines.append(f"> **Example:** {ag.explanation.example}")
            lines.append("")

    # Dimensions
    lines.append("## Dimensions")
    lines.append("")
    lines.append("| Dimension | Score | Weak tables |")
    lines.append("|---|---|---|")
    for dd in a.dimension_detail:
        score_str = str(dd.score) if dd.score is not None else "N/A"
        weak_str = ", ".join(dd.weak_tables) if dd.weak_tables else "—"
        lines.append(f"| {dd.label} | {score_str} | {weak_str} |")
    lines.append("")

    # Tables
    lines.append("## Tables")
    lines.append("")
    lines.append("| Table | Rows | Governed | Base | Class |")
    lines.append("|---|---|---|---|---|")
    for t in a.tables:
        governed_str = str(t.overall_score) if t.klass != "reference" else "—"
        base_str = str(t.base_score if t.base_score is not None else t.overall_score) if t.klass != "reference" else "—"
        lines.append(f"| {t.table_name} | {t.row_count:,} | {governed_str} | {base_str} | {t.klass} |")
    lines.append("")

    lines.append("---")
    lines.append("*Generated by ARC Evaluator. Scores are deterministic.*")
    return "\n".join(lines)


@router.post("/markdown")
async def export_markdown(
    assessment: SchemaAssessment,
    _user: CurrentUser = Depends(require_user),
) -> Response:
    """Render the assessment as a markdown action plan. The FE downloads this
    directly — it never rebuilds markdown on the client."""
    md = _render_markdown(assessment)
    return Response(
        content=md,
        media_type="text/markdown",
        headers={"Content-Disposition": "attachment; filename=ai-readiness-report.md"},
    )


@router.get("/{run_id}.json")
async def export_json(
    run_id: str,
    user: CurrentUser = Depends(require_user),
) -> Response:
    """Return the stored assessment JSON for a given run_id from history.

    This is the server-side export — the canonical result_json persisted at
    assessment time. Returns 404 if the run doesn't exist or doesn't belong
    to the requesting user (unless superuser).
    """
    from fastapi import HTTPException

    from config import settings
    from db.engine import get_session

    if not settings.history_db_enabled:
        raise HTTPException(status_code=501, detail="History DB not enabled.")

    from db.history_store import get_run_detail

    async with get_session() as session:
        run = await get_run_detail(session, run_id=run_id, user_id=user.user_id)

    if not run:
        raise HTTPException(status_code=404, detail="Run not found.")

    result_json = run.get("result_json")
    if not result_json:
        raise HTTPException(status_code=404, detail="No result stored for this run.")

    import json
    return Response(
        content=json.dumps(result_json, indent=2),
        media_type="application/json",
        headers={"Content-Disposition": f"attachment; filename=assessment-{run_id}.json"},
    )
